### ISSUE TITLE
CG Charter Filename

### ISSUE THREAD

**Issue by evanp** [swicg/potential-charters#20]
The charter file has a long numeric suffix (1727386911). It doesn't seem to be a datestamp; maybe it's a unix timestamp? Regardless, we have a version control system here, so I think just "CGCharter.html" is fine.

**Comment by gobengo** [comment]
> we have a version control system here, so I think just "CGCharter.html" is fine.

The reason there is a nonce is because this repository may have multiple CG Charters, just like it has multiple WG Charters. The name has a nonce to encourage there to not be a single `CGCharter.html` unless the group reaches consensus on a filename.

I recommend doing nothing and instead of spending time on the file names to spend time on the contents of a specific charter that may eventually have group consensus.

**Comment by evanp** [comment]
@gobengo so, do we move it to CGCharter.html when it actually is the charter?

**Comment by evanp** [comment]
@gobengo could you add this explanation to the README.md?

**Comment by evanp** [comment]
Also, we did reach consensus that this document is the one we want to work from, in our October meeting.

**Comment by gobengo** [comment]
> @gobengo so, do we move it to CGCharter.html when it actually is the charter?

maybe? I think when there is a charter it might make more sense to remove it altogether from potential-charters or replace the contents with a link to the final charter in a repo that is not titled `potential-charters`.

**Comment by evanp** [comment]
Oh, yeah, that would make sense. There are a few, like `general`, `processes`, or even `www`. I guess @dmitrizagidulin and @nightpool can decide on that.

**Comment by dmitrizagidulin** [comment]
Sounds good (I propose we close this issue meanwhile).
